name: Build and Release C++ Binaries for ARM64 and x86_64

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - architecture: amd64
            target: x86_64-linux-gnu
          - architecture: arm64
            target: aarch64-linux-gnu
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-aarch64-linux-gnu gcc-aarch64-linux-gnu
          sudo apt-get install -y g++-multilib gcc-multilib
          sudo apt-get install -y build-essential libcurl4-openssl-dev libjson-c-dev

      - name: Build
        run: |
          make ARCH=${{ matrix.architecture }}
        env:
          CC: ${{ matrix.target }}-gcc
          CXX: ${{ matrix.target }}-g++
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dgnsm-${{ matrix.architecture }}
          path: path/to/your/binary
